[build]
  base = "client"
  publish = "build"
  command = "npm cache clean --force && npm install --legacy-peer-deps --no-fund && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_CONFIG_FUND = "false"
  REACT_APP_DEMO_MODE = "true"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_DEBUG = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 